apiVersion: v2
name: sales
description: A Helm chart for deploying the Sales microservice to Minikube
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - sales
  - microservice
  - minikube
