apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app: {{ include "gateway.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gateway.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "gateway.fullname" . }}
    spec:
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ .Values.env.ASPNETCORE_ENVIRONMENT }}"
            - name: ASPNETCORE_URLS
              value: "{{ .Values.env.ASPNETCORE_URLS }}"
            - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
              value: "{{ .Values.env.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
            - name: Identity__Authority
              value: "{{ index .Values.env "Identity__Authority" }}"
            - name: RabbitMQ__Host
              value: "{{ index .Values.env "RabbitMQ__Host" }}"
            - name: RabbitMQ__Username
              value: "{{ index .Values.env "RabbitMQ__Username" }}"
            - name: RabbitMQ__Password
              value: "{{ index .Values.env "RabbitMQ__Password" }}"
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 5
