apiVersion: v1
kind: Service
metadata:
  name: '{{ include "sqlserver.fullname" . }}'
  labels:
    app: '{{ include "sqlserver.fullname" . }}'
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: '{{ include "sqlserver.fullname" . }}'
  ports:
    - name: mssql
      port: {{ .Values.service.port }}
      targetPort: 1433
