// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rsk.Saml.IdentityProvider.Storage.EntityFramework.DbContexts;

#nullable disable

namespace microservices.identity.Migrations.SamlConfiguration
{
    [DbContext(typeof(SamlConfigurationDbContext))]
    partial class SamlConfigurationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ArtifactResolutionService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Binding")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderArtifactResolutionServices", (string)null);
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.AssertionConsumerService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Binding")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderAssertionConsumerServices", (string)null);
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.SamlClaimMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NewClaimType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("OriginalClaimType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderClaimMappings", (string)null);
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowIdpInitiatedSso")
                        .HasColumnType("bit");

                    b.Property<string>("ArtifactDeliveryBindingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EncryptAssertions")
                        .HasColumnType("bit");

                    b.Property<byte[]>("EncryptionCertificate")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameIdentifierFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RequireAuthenticationRequestsSigned")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireSamlMessageDestination")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequireSignedArtifactResolveRequests")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequireSignedArtifactResponses")
                        .HasColumnType("bit");

                    b.Property<bool>("SignAssertions")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EntityId")
                        .IsUnique();

                    b.ToTable("ServiceProviders", (string)null);
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.SigningCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Certificate")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderSignCertificates", (string)null);
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.SingleLogoutService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Binding")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderSingleLogoutServices", (string)null);
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ArtifactResolutionService", b =>
                {
                    b.HasOne("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("ArtifactResolutionServices")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.AssertionConsumerService", b =>
                {
                    b.HasOne("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("AssertionConsumerServices")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.SamlClaimMap", b =>
                {
                    b.HasOne("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("ClaimsMapping")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.SigningCertificate", b =>
                {
                    b.HasOne("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("SigningCertificates")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.SingleLogoutService", b =>
                {
                    b.HasOne("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("SingleLogoutServices")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ServiceProvider", b =>
                {
                    b.Navigation("ArtifactResolutionServices");

                    b.Navigation("AssertionConsumerServices");

                    b.Navigation("ClaimsMapping");

                    b.Navigation("SigningCertificates");

                    b.Navigation("SingleLogoutServices");
                });
#pragma warning restore 612, 618
        }
    }
}
