sqlserver:
  enabled: true
  image:
    repository: mcr.microsoft.com/mssql/server
    tag: 2022-latest
  service:
    type: ClusterIP
    port: 1433
  persistence:
    enabled: true

rabbitmq:
  enabled: true
  image:
    repository: rabbitmq
    tag: 3.11-management
  service:
    type: ClusterIP
    port: 5672
    managementPort: 15672
  persistence:
    enabled: true

sales:
  enabled: true
  image:
    repository: sales
    tag: latest
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080

identity:
  enabled: true
  image:
    repository: identity
    tag: latest
  service:
    type: ClusterIP
    port: 443
    targetPort: 8080
  ingress:
    enabled: true
    host: microservices.identity.local
    tls:
      secretName: identity-tls

gateway:
  enabled: true
  image:
    repository: gateway
    tag: latest
  service:
    type: ClusterIP
    port: 443
    targetPort: 8080
  ingress:
    enabled: true
    host: blazorapp.gateway.local
    tls:
      secretName: gateway-tls
