apiVersion: v1
kind: Service
metadata:
  name: '{{ include "rabbitmq.fullname" . }}'
  labels:
    app: '{{ include "rabbitmq.fullname" . }}'
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: '{{ include "rabbitmq.fullname" . }}'
  ports:
    - name: amqp
      port: {{ .Values.service.port }}
      targetPort: 5672
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: 15672
